"""add_permissions_and_superadmin

Revision ID: 2a1a2b1e43b5
Revises: 1bc2c956fedf
Create Date: 2026-03-21 16:05:00.511622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1a2b1e43b5'
down_revision: Union[str, None] = '1bc2c956fedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add 'superadmin' to the user_role enum (PostgreSQL requires special handling)
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'superadmin'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('manage_quizzes', 'manage_knowledge', 'view_results', 'manage_users', 'manage_admins', name='permission_type'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_user_id'), 'admin_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_permissions_user_id'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    # ### end Alembic commands ###
