"""add_onboarding_tracks

Revision ID: 63418eadb1ed
Revises: 9bcd63870810
Create Date: 2026-03-22 13:22:14.766621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63418eadb1ed'
down_revision: Union[str, None] = '9bcd63870810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('position_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['onboarding_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_stages_track_id'), 'track_stages', ['track_id'], unique=False)
    op.create_table('user_tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['track_id'], ['onboarding_tracks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'track_id', name='uq_user_track')
    )
    op.create_index(op.f('ix_user_tracks_track_id'), 'user_tracks', ['track_id'], unique=False)
    op.create_index(op.f('ix_user_tracks_user_id'), 'user_tracks', ['user_id'], unique=False)
    op.create_table('stage_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.Enum('article', 'quiz', 'checklist', 'url', name='onboarding_item_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('article_id', sa.Uuid(), nullable=True),
    sa.Column('quiz_id', sa.Uuid(), nullable=True),
    sa.Column('external_url', sa.String(length=512), nullable=True),
    sa.Column('checklist_items', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['track_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_items_stage_id'), 'stage_items', ['stage_id'], unique=False)
    op.create_table('user_item_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_track_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['stage_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_track_id'], ['user_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_track_id', 'item_id', name='uq_user_track_item')
    )
    op.create_index(op.f('ix_user_item_progress_item_id'), 'user_item_progress', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_item_progress_user_track_id'), 'user_item_progress', ['user_track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_item_progress_user_track_id'), table_name='user_item_progress')
    op.drop_index(op.f('ix_user_item_progress_item_id'), table_name='user_item_progress')
    op.drop_table('user_item_progress')
    op.drop_index(op.f('ix_stage_items_stage_id'), table_name='stage_items')
    op.drop_table('stage_items')
    op.drop_index(op.f('ix_user_tracks_user_id'), table_name='user_tracks')
    op.drop_index(op.f('ix_user_tracks_track_id'), table_name='user_tracks')
    op.drop_table('user_tracks')
    op.drop_index(op.f('ix_track_stages_track_id'), table_name='track_stages')
    op.drop_table('track_stages')
    op.drop_table('onboarding_tracks')
    # ### end Alembic commands ###
