"""add_manager_login_id_to_users

Revision ID: 696109a625ab
Revises: 15acf0aa86ec
Create Date: 2026-03-21 17:41:26.242390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696109a625ab'
down_revision: Union[str, None] = '15acf0aa86ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('manager_login_id', sa.String(length=20), nullable=True, comment='Числовий ID з панелі менеджера (1001, 1002...)'))
    op.create_index(op.f('ix_users_manager_login_id'), 'users', ['manager_login_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_manager_login_id'), table_name='users')
    op.drop_column('users', 'manager_login_id')
    # ### end Alembic commands ###
