"""add_question_order_to_attempt

Revision ID: 9bcd63870810
Revises: ef7ba7a7aaaf
Create Date: 2026-03-22 10:12:57.533338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcd63870810'
down_revision: Union[str, None] = 'ef7ba7a7aaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('question_order', sa.Text(), nullable=True, comment='JSON array of question UUIDs in shuffled order for this attempt'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'question_order')
    # ### end Alembic commands ###
