"""add_shuffle_questions_to_quiz

Revision ID: ef7ba7a7aaaf
Revises: 696109a625ab
Create Date: 2026-03-22 10:07:47.628873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7ba7a7aaaf'
down_revision: Union[str, None] = '696109a625ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('shuffle_questions', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'shuffle_questions')
    # ### end Alembic commands ###
